---

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: ../CryptoMaterials/crypto-config/ordererOrganizations/orderer-org/msp
- &Org1
  Name: Org1MSP
  ID: Org1MSP
  MSPDir: ../CryptoMaterials/crypto-config/peerOrganizations/org1/msp
  AnchorPeers:
  - Host: org1-peer-0
    Port: 7051
- &Org2
  Name: Org2MSP
  ID: Org2MSP
  MSPDir: ../CryptoMaterials/crypto-config/peerOrganizations/org2/msp
  AnchorPeers:
  - Host: org2-peer-0
    Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Capabilities:
  Channel: &ChannelCapabilities
    V1_1: true
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_1: true
    V1_3: true

# Application: &ApplicationDefaults
#   # ACLs: &ACLsDefault
#   #   peer/Propose: /Channel/Application/MyPolicy1
#   # Policies: &ApplicationDefaultPolicies
#   #       Readers:
#   #           Type: ImplicitMeta
#   #           Rule: "ANY Readers"
#   #       Writers:
#   #           Type: ImplicitMeta
#   #           Rule: "ANY Writers"
#   #       Admins:
#   #           Type: ImplicitMeta
#   #           Rule: "MAJORITY Admins"
#   #       MyPolicy1:
#   #           Type: Signature
#   #           Rule: "OR('ShopOrgMSP.member')"
#   Organizations:
#   Capabilities:
#         <<: *ApplicationCapabilities

Profiles:
  OrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
      Capabilities:
         <<: *OrdererCapabilities
    Consortiums:
      InsuranceConsortium:
        Organizations:
        - *Org1
        - *Org2
        
  GlobalChannel:
    Consortium: InsuranceConsortium
    Application:
      # <<: *ApplicationDefaults
      Organizations:
      - *Org1
      - *Org2
