OrdererOrgs:
- Name: OrdererOrg
  Domain: orderer-org
  CommonName: orderer-org
  Specs:
  - Hostname: orderer-0
    CommonName: "{{.Hostname}}"

PeerOrgs:
- Name: Org1
  Domain: org1
  Specs:
  - Hostname: org1-peer-0
    CommonName: "{{.Hostname}}"
- Name: Org2
  Domain: org2
  Specs:
  - Hostname: org2-peer-0
    CommonName: "{{.Hostname}}"
